### ISSUE TITLE
remove Context param from SQLiteOpenHelper

### ISSUE THREAD

**Issue by kmitj** [bloomberg/selekt#386]
ISQLiteOpenHelper databaseName change to db file or db path .
in SQLiteOpenHelper i can't set my database folder.

**Comment by kennethshackleton** [comment]
You can pass a `ContextWrapper` that has [`getDatabasePath(String)`](https://developer.android.com/reference/android/content/ContextWrapper#getDatabasePath(java.lang.String)) overridden.

We encounter this kind of issue in the unit tests, see for instance [SupportSQLiteOpenHelperFactoryTest.context](https://github.com/bloomberg/selekt/blob/main/AndroidLib/src/test/kotlin/com/bloomberg/selekt/android/support/SupportSQLiteOpenHelperFactoryTest.kt#L79).

**Comment by kmitj** [comment]
You only need the Android Context to get the database file. if you have the full path to the database files you don't need the context. Right?

**Comment by kennethshackleton** [comment]
The constructor taking the `Context` here is consistent with Android's [android.database.sqlite.SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper#SQLiteOpenHelper(android.content.Context,%20java.lang.String,%20int,%20android.database.sqlite.SQLiteDatabase.OpenParams)). If you only need the `Context` for the database folder, you can use `ContextWrapper` to create the API you want in your project.

**Comment by shod1yor** [comment]
> The constructor taking the `Context` here is consistent with Android's [android.database.sqlite.SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper#SQLiteOpenHelper(android.content.Context,%20java.lang.String,%20int,%20android.database.sqlite.SQLiteDatabase.OpenParams)). If you only need the `Context` for the database folder, you can use `ContextWrapper` to create the API you want in your project.

Please remove context from params, it's not used anyway

**Comment by kmitj** [comment]
> You only need the Android Context to get the database file. if you have the full path to the database files you don't need the context. Right?

yes. but in our architecture the sqlite open call is from the main module and main module does not know about Context.  can you create another constructor without Context or make setPageSizeExponent, setJournalMode methods public?
